language: python
env: # These should match the tox env list
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install: pip install coveralls tox --use-mirrors
script: tox
after_success:
    - coveralls
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
